### ISSUE TITLE
Peer to peer code review (Private_events)

### ISSUE THREAD

**Issue by dev1980** [dev1980/private_events#3]
Please comment on this .

**Comment by vieiramanda11** [comment]
Well done with the project so far. Nothing to add.

**Comment by AndresFMoya** [comment]
Great job Brham. Your code is clean and easy to read. Nothing to add.

**Comment by ansaryergesh** [comment]
no comments:) everything is clear

**Comment by dev1980** [comment]
Peer to Peer code review completed.
